"use client";
import Image from "next/image";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { Lesson, NamedElement, TimetablePayload } from "@/lib/types";
import { addDays, isoDate, mondayFor } from "@/lib/date";
import { applyCourseFilter } from "@/lib/courses";
import { getLessonStatus } from "@/lib/lesson-status";
import { COURSE_FILTER_STORAGE_KEY, normalizeCourseFilter, parseCourseFilter, serializeCourseFilter, type CourseFilter } from "@/lib/local-filters";
import { SiteFooter } from "@/components/site-footer";

const weekDays = ["Montag","Dienstag","Mittwoch","Donnerstag","Freitag"];
function formatTime(value:number){return `${String(Math.floor(value/100)).padStart(2,"0")}:${String(value%100).padStart(2,"0")}`}
function dateNumber(date:Date){return date.getFullYear()*10000+(date.getMonth()+1)*100+date.getDate()}
function names(values: NamedElement[] = []) { return values.map(v=>v.longname||v.name).join(", ") || "–"; }
export function Dashboard({displayName}:{displayName:string}) { const router=useRouter(); const [week,setWeek]=useState(mondayFor()); const [mode,setMode]=useState<"week"|"day">("week"); const [day,setDay]=useState(Math.min(4,Math.max(0,(new Date().getDay()||1)-1))); const [data,setData]=useState<TimetablePayload|null>(null); const [courseFilter,setCourseFilter]=useState<CourseFilter>({selectedCourseKeys:[],filterEnabled:false}); const [selected,setSelected]=useState<Lesson|null>(null); const [filtersOpen,setFiltersOpen]=useState(false); const [logoutOpen,setLogoutOpen]=useState(false); const [logoutBusy,setLogoutBusy]=useState(false); const [logoutError,setLogoutError]=useState(""); const [busy,setBusy]=useState(true); const [error,setError]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{const response=await fetch(`/api/timetable?week=${isoDate(week)}`,{cache:"no-store"});const body=await response.json();if(response.status===401){router.replace("/login");return}if(!response.ok)throw new Error(body.error);setData(body)}catch(e){setError(e instanceof Error?e.message:"Stundenplan konnte nicht geladen werden.")}finally{setBusy(false)}},[week,router]);
 // The effect synchronizes the selected week with the remote timetable API.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{load()},[load]);
 useEffect(()=>{try{
   // The browser owns filter preferences; they are intentionally independent of the login.
   // eslint-disable-next-line react-hooks/set-state-in-effect
   setCourseFilter(parseCourseFilter(window.localStorage.getItem(COURSE_FILTER_STORAGE_KEY)));
  }catch{}const sync=(event:StorageEvent)=>{if(event.key===COURSE_FILTER_STORAGE_KEY)setCourseFilter(parseCourseFilter(event.newValue))};window.addEventListener("storage",sync);return()=>window.removeEventListener("storage",sync)},[]);
 const filteredLessons=useMemo(()=>applyCourseFilter(data?.lessons||[],courseFilter.selectedCourseKeys,courseFilter.filterEnabled),[data,courseFilter]);
 const lessonsByDay=useMemo(()=>weekDays.map((_,i)=>filteredLessons.filter(l=>l.date===dateNumber(addDays(week,i))).sort((a,b)=>a.startTime-b.startTime)),[filteredLessons,week]);
 function saveFilters(keys:string[],enabled:boolean){const next=normalizeCourseFilter({selectedCourseKeys:keys,filterEnabled:enabled});setCourseFilter(next);try{window.localStorage.setItem(COURSE_FILTER_STORAGE_KEY,serializeCourseFilter(next))}catch{}}
 async function logout(){setLogoutBusy(true);setLogoutError("");try{const response=await fetch("/api/auth/logout",{method:"POST"});if(!response.ok)throw new Error();router.replace("/login");router.refresh()}catch{setLogoutError("Das Abmelden hat nicht geklappt. Bitte versuche es erneut.");setLogoutBusy(false)}}
 function openLogout(){setLogoutError("");setLogoutOpen(true)}
 function closeLogout(){if(!logoutBusy)setLogoutOpen(false)}
 return <div className="app-layout"><main className="app-shell"><header className="topbar"><a className="brand" href="/stundenplan"><Image className="brand-icon" src="/untiplan-logo.png" alt="" width={36} height={36} priority/><b>Untiplan</b></a><div className="user"><span>{displayName}</span><button className="ghost" onClick={openLogout} aria-haspopup="dialog">Abmelden</button></div></header><section className="toolbar"><div><p className="eyebrow">Stundenplan</p><h1>{week.toLocaleDateString("de-DE",{day:"2-digit",month:"long"})} – {addDays(week,4).toLocaleDateString("de-DE",{day:"2-digit",month:"long",year:"numeric"})}</h1>{data?.schoolYear&&<p className="muted">Schuljahr {data.schoolYear}{data.latestImportTime?` · Stand ${new Date(data.latestImportTime).toLocaleString("de-DE")}`:""}</p>}</div><div className="toolbar-actions"><button className="ghost" onClick={()=>setWeek(addDays(week,-7))} aria-label="Vorherige Woche">←</button><button className="ghost" onClick={()=>setWeek(mondayFor())}>Heute</button><button className="ghost" onClick={()=>setWeek(addDays(week,7))} aria-label="Nächste Woche">→</button><button className="filter-button" onClick={()=>setFiltersOpen(true)}>Filter {courseFilter.filterEnabled?<span className="dot"/>:null}</button></div></section><nav className="view-tabs"><button className={mode==="week"?"active":""} onClick={()=>setMode("week")}>Woche</button><button className={mode==="day"?"active":""} onClick={()=>setMode("day")}>Tag</button></nav>
 {error&&<div className="notice error">{error}<button onClick={load}>Erneut versuchen</button></div>}{busy?<div className="loader">Stundenplan wird geladen …</div>:mode==="week"?<div className="week-grid">{weekDays.map((label,i)=><DayColumn key={label} label={label} date={addDays(week,i)} lessons={lessonsByDay[i]} onSelect={setSelected}/>)}</div>:<><div className="day-tabs">{weekDays.map((label,i)=><button key={label} className={day===i?"active":""} onClick={()=>setDay(i)}>{label.slice(0,2)}</button>)}</div><div className="day-view"><DayColumn label={weekDays[day]} date={addDays(week,day)} lessons={lessonsByDay[day]} onSelect={setSelected}/></div></>}
 {filtersOpen&&data&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setFiltersOpen(false)}}><aside className="drawer"><div className="drawer-head"><div><p className="eyebrow">Ansicht anpassen</p><h2>Kursfilter</h2></div><button className="icon-button" onClick={()=>setFiltersOpen(false)}>×</button></div><label className="switch-row"><span><b>Filter aktivieren</b><small>Nur ausgewählte Kurse auf diesem Gerät anzeigen</small></span><input type="checkbox" checked={courseFilter.filterEnabled} onChange={e=>saveFilters(courseFilter.selectedCourseKeys,e.target.checked)}/></label><div className="course-list">{data.courses.length?data.courses.map(course=><label key={course.key} className="course-option"><input type="checkbox" checked={courseFilter.selectedCourseKeys.includes(course.key)} onChange={e=>saveFilters(e.target.checked?[...courseFilter.selectedCourseKeys,course.key]:courseFilter.selectedCourseKeys.filter(k=>k!==course.key),courseFilter.filterEnabled)}/><span><b>{course.subject}</b><small>{course.teacher}</small></span></label>):<p className="muted">In diesem Zeitraum wurden keine Kurse gefunden.</p>}</div><button className="ghost full" onClick={()=>saveFilters([],false)}>Filter zurücksetzen</button></aside></div>}
 {selected&&<LessonDialog lesson={selected} close={()=>setSelected(null)}/>} {logoutOpen&&<LogoutDialog close={closeLogout} confirm={logout} busy={logoutBusy} error={logoutError}/>}</main><SiteFooter /></div> }
function DayColumn({label,date,lessons,onSelect}:{label:string;date:Date;lessons:Lesson[];onSelect:(l:Lesson)=>void}){return <section className="day-column"><header><b>{label}</b><span>{date.toLocaleDateString("de-DE",{day:"2-digit",month:"2-digit"})}</span></header><div className="lesson-stack">{lessons.length?lessons.map(l=><button key={`${l.id}-${l.startTime}`} className={`lesson ${getLessonStatus(l)}`} onClick={()=>onSelect(l)}><span className="time">{formatTime(l.startTime)}–{formatTime(l.endTime)}</span><strong>{names(l.su)}</strong><span>{names(l.te)}</span><span className="room">{names(l.ro)}</span>{getLessonStatus(l)!=="normal"&&<em>{getLessonStatus(l)==="cancelled"?"Entfällt":getLessonStatus(l)==="substitution"?"Vertretung":"Änderung"}</em>}</button>):<div className="empty">Keine Stunden</div>}</div></section>}
function LessonDialog({lesson,close}:{lesson:Lesson;close:()=>void}){const status=getLessonStatus(lesson);return <div className="overlay dialog-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><article className="dialog"><div className="drawer-head"><div><p className="eyebrow">Unterrichtsdetails</p><h2>{names(lesson.su)}</h2></div><button className="icon-button" onClick={close}>×</button></div><span className={`status ${status}`}>{status==="cancelled"?"Ausfall":status==="substitution"?"Vertretung":status==="normal"?"Planmäßig":"Geändert"}</span><dl><div><dt>Zeit</dt><dd>{formatTime(lesson.startTime)}–{formatTime(lesson.endTime)} Uhr</dd></div><div><dt>Lehrkraft</dt><dd>{names(lesson.te)}</dd></div><div><dt>Raum</dt><dd>{names(lesson.ro)}</dd></div><div><dt>Klasse</dt><dd>{names(lesson.kl)}</dd></div><div><dt>Gruppe</dt><dd>{lesson.sg||"–"}</dd></div><div><dt>Hinweis</dt><dd>{lesson.substText||lesson.info||lesson.lstext||"–"}</dd></div></dl></article></div>}
function LogoutDialog({close,confirm,busy,error}:{close:()=>void;confirm:()=>void;busy:boolean;error:string}){return <div className="overlay dialog-overlay logout-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}} onKeyDown={e=>{if(e.key==="Escape")close()}}><article className="logout-dialog" role="alertdialog" aria-modal="true" aria-labelledby="logout-title" aria-describedby="logout-description"><div className="logout-icon" aria-hidden="true">!</div><div className="logout-copy"><p className="eyebrow">Sitzung beenden</p><h2 id="logout-title">Wirklich abmelden?</h2><p id="logout-description" className="muted">Du wirst zur Anmeldung zurückgebracht und musst dich erneut anmelden, um deinen Stundenplan zu sehen.</p>{error&&<p className="logout-error" role="alert">{error}</p>}</div><div className="logout-actions"><button className="ghost" onClick={close} disabled={busy} autoFocus>Abbrechen</button><button className="danger-button" onClick={confirm} disabled={busy}>{busy?"Wird abgemeldet …":"Ja, abmelden"}</button></div></article></div>}
