"use client";
import { getLessonStatus } from "@/lib/lesson-status";
import { useModalFocus } from "@/lib/use-modal-focus";
import { lessonChangeSummary } from "@/lib/timetable-view";
import type { Course, Lesson } from "@/lib/types";
import type { CourseFilter } from "@/lib/local-filters";
import { formatTime, names } from "@/components/timetable-views";

export type AccountSummary={id:string;displayName:string;username:string;school:string;active:boolean};

export function FilterDialog({courseFilter,courseOptions,visibleCourseOptions,courseSearch,setCourseSearch,saveFilters,offlineEnabled,updateOffline,notificationsEnabled,updateNotifications,close}:{courseFilter:CourseFilter;courseOptions:Course[];visibleCourseOptions:Course[];courseSearch:string;setCourseSearch:(value:string)=>void;saveFilters:(keys:string[],enabled:boolean)=>void;offlineEnabled:boolean;updateOffline:(enabled:boolean)=>void;notificationsEnabled:boolean;updateNotifications:(enabled:boolean)=>void;close:()=>void}) {
  const ref=useModalFocus(close);
  return <div className="overlay" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><aside ref={ref} className="drawer" role="dialog" aria-modal="true" aria-labelledby="filter-title"><div className="drawer-head"><div><p className="eyebrow">Ansicht anpassen</p><h2 id="filter-title">Optionen</h2></div><button className="icon-button" onClick={close} aria-label="Optionen schließen">×</button></div><section className="option-section"><h3>Offline & Änderungen</h3><label className="switch-row"><span><b>Stundenpläne speichern</b><small>Geladene Wochen verschlüsselt auf diesem Gerät verfügbar machen</small></span><input type="checkbox" checked={offlineEnabled} onChange={event=>updateOffline(event.target.checked)}/></label><label className="switch-row"><span><b>Änderungen melden</b><small>Bei Aktualisierungen über neu erkannte Änderungen informieren</small></span><input type="checkbox" checked={notificationsEnabled} onChange={event=>updateNotifications(event.target.checked)}/></label></section><section className="option-section"><h3>Kursfilter</h3><label className="switch-row"><span><b>Filter aktivieren</b><small>Nur ausgewählte Kurse auf diesem Gerät anzeigen</small></span><input type="checkbox" checked={courseFilter.filterEnabled} disabled={!courseFilter.selectedCourseKeys.length} onChange={event=>saveFilters(courseFilter.selectedCourseKeys,event.target.checked)}/></label><label className="course-search"><span>Kurse suchen</span><input type="search" value={courseSearch} onChange={event=>setCourseSearch(event.target.value)} placeholder="Fach, Lehrkraft oder Schlüssel" /></label><div className="course-list">{courseOptions.length?visibleCourseOptions.length?visibleCourseOptions.map(course=><label key={course.key} className="course-option"><input type="checkbox" checked={courseFilter.selectedCourseKeys.includes(course.key)} onChange={event=>saveFilters(event.target.checked?[...courseFilter.selectedCourseKeys,course.key]:courseFilter.selectedCourseKeys.filter(key=>key!==course.key),event.target.checked||courseFilter.selectedCourseKeys.length>1?courseFilter.filterEnabled:false)}/><span><b>{course.subject}</b><small>{course.teacher}</small></span></label>):<p className="muted">Keine Kurse für die Suche gefunden.</p>:<p className="muted">In diesem Zeitraum wurden keine Kurse gefunden.</p>}</div><button className="ghost full" onClick={()=>saveFilters([],false)}>Filter zurücksetzen</button></section></aside></div>
}

export function LessonDialog({lesson,close}:{lesson:Lesson;close:()=>void}) {
  const status=getLessonStatus(lesson),ref=useModalFocus(close);
  return <div className="overlay dialog-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><article ref={ref} className="dialog" role="dialog" aria-modal="true" aria-labelledby="lesson-title"><div className="drawer-head"><div><p className="eyebrow">Unterrichtsdetails</p><h2 id="lesson-title">{names(lesson.su)}</h2></div><button className="icon-button" onClick={close} aria-label="Unterrichtsdetails schließen">×</button></div><span className={`status ${status}`}>{status==="cancelled"?"Ausfall":status==="substitution"?"Vertretung":status==="normal"?"Planmäßig":"Geändert"}</span>{status!=="normal"&&<p className="change-detail">{lessonChangeSummary(lesson)}</p>}<dl><div><dt>Zeit</dt><dd>{formatTime(lesson.startTime)}–{formatTime(lesson.endTime)} Uhr</dd></div><div><dt>Lehrkraft</dt><dd>{names(lesson.te)}</dd></div><div><dt>Raum</dt><dd>{names(lesson.ro)}</dd></div><div><dt>Klasse</dt><dd>{names(lesson.kl)}</dd></div><div><dt>Gruppe</dt><dd>{lesson.sg||"–"}</dd></div><div><dt>Hinweis</dt><dd>{lesson.substText||lesson.info||lesson.lstext||"–"}</dd></div></dl></article></div>
}

export function AccountDialog({accounts,loading,switchingAccountId,error,close,switchAccount}:{accounts:AccountSummary[];loading:boolean;switchingAccountId:string;error:string;close:()=>void;switchAccount:(accountId:string)=>void}) {
  const ref=useModalFocus(close);
  return <div className="overlay dialog-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><article ref={ref} className="account-dialog" role="dialog" aria-modal="true" aria-labelledby="accounts-title"><div className="drawer-head"><div><p className="eyebrow">Angemeldete Konten</p><h2 id="accounts-title">Konto wechseln</h2></div><button className="icon-button" onClick={close} disabled={Boolean(switchingAccountId)} aria-label="Konten schließen">×</button></div><p className="muted account-hint">Jedes Konto behält seine eigenen Einstellungen.</p>{loading?<div className="account-loading">Konten werden geladen …</div>:<div className="account-list">{accounts.map(account=><button key={account.id} className={`account-option ${account.active?"active":""}`} onClick={()=>switchAccount(account.id)} disabled={account.active||Boolean(switchingAccountId)}><span className="account-avatar" aria-hidden="true">{account.displayName.trim().charAt(0).toLocaleUpperCase("de")||"?"}</span><span className="account-copy"><b>{account.displayName}</b><small>{account.username} · {account.school}</small></span><span className="account-state">{account.active?"Aktiv":switchingAccountId===account.id?"Wechsel …":"Wechseln"}</span></button>)}</div>}{error&&<p className="logout-error" role="alert">{error}</p>}<a className="primary account-add" href="/login?add=1">+ Weiteres Konto hinzufügen</a></article></div>
}

export function LogoutDialog({accountName,close,confirm,busy,error}:{accountName:string;close:()=>void;confirm:()=>void;busy:boolean;error:string}) {
  const ref=useModalFocus(close);
  return <div className="overlay dialog-overlay logout-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><article ref={ref} className="logout-dialog" role="alertdialog" aria-modal="true" aria-labelledby="logout-title" aria-describedby="logout-description"><div className="logout-icon" aria-hidden="true">!</div><div className="logout-copy"><p className="eyebrow">Konto abmelden</p><h2 id="logout-title">Wirklich abmelden?</h2><p id="logout-description" className="muted">Du meldest das Konto <strong>„{accountName}“</strong> ab. Zugehörige lokale Einstellungen und Offline-Daten werden gelöscht. Deine anderen Konten bleiben unverändert.</p>{error&&<p className="logout-error" role="alert">{error}</p>}</div><div className="logout-actions"><button className="ghost" onClick={close} disabled={busy}>Abbrechen</button><button className="danger-button" onClick={confirm} disabled={busy}>{busy?"Wird abgemeldet …":"Konto abmelden"}</button></div></article></div>
}
