"use client";
import Image from "next/image";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Course, Lesson, NamedElement, TimetableElement, TimetableElementSelection, TimetableElementType, TimetablePayload } from "@/lib/types";
import { addDays, isoDate, mondayFor } from "@/lib/date";
import { applyCourseFilter } from "@/lib/courses";
import { getLessonStatus } from "@/lib/lesson-status";
import { courseFilterStorageKey, LEGACY_COURSE_FILTER_STORAGE_KEY, normalizeCourseFilter, parseCourseFilter, serializeCourseFilter, type CourseFilter } from "@/lib/local-filters";
import { parseTimetableSelection, parseTimetableViewMode, serializeTimetableSelection, serializeTimetableViewMode, timetableSelectionStorageKey, timetableViewModeStorageKey, type TimetableViewMode } from "@/lib/local-timetable";
import { clearOfflineTimetables, offlineTimetablePreferenceKey, readOfflineTimetable, saveOfflineTimetable } from "@/lib/offline-timetable";
import { changeSnapshot, newChanges, notificationPreferenceKey, notificationSnapshotKey } from "@/lib/change-notifications";
import { downloadBlob, downloadTextFile, lessonsToIcs, timetablePng, timetableShareText } from "@/lib/timetable-export";
import { namedElementLabel, sortTimetableElements, timetableElementLabel } from "@/lib/timetable-elements";
import { changedLessons, holidaysForDate, lessonChangeSummary, positionLessons, timetableBounds, timeToMinutes, type TimelineBounds } from "@/lib/timetable-view";
import { SiteFooter } from "@/components/site-footer";

const weekDays = ["Montag","Dienstag","Mittwoch","Donnerstag","Freitag"];
const timetableElementLabels:Record<TimetableElementType,string> = {1:"Klassen",2:"Lehrkräfte",3:"Fächer",4:"Räume",5:"Schüler*innen"};
type AccountSummary = { id:string; displayName:string; username:string; school:string; active:boolean };
function formatTime(value:number){return `${String(Math.floor(value/100)).padStart(2,"0")}:${String(value%100).padStart(2,"0")}`}
function dateNumber(date:Date){return date.getFullYear()*10000+(date.getMonth()+1)*100+date.getDate()}
function names(values: NamedElement[] = []) { return values.map(namedElementLabel).join(", ") || "–"; }
function relativeTime(timestamp:number,now:number){const minutes=Math.max(0,Math.floor((now-timestamp)/60000));return minutes<1?"gerade eben":minutes===1?"vor 1 Minute":minutes<60?`vor ${minutes} Minuten`:new Date(timestamp).toLocaleString("de-DE")}
function useModalFocus(close:()=>void) {
 const ref=useRef<HTMLElement>(null);
 const closeRef=useRef(close);
 useEffect(()=>{closeRef.current=close},[close]);
 useEffect(()=>{const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;const root=ref.current;if(!root)return;const focusable=()=>[...root.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])')];focusable()[0]?.focus();const keydown=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();closeRef.current();return}if(event.key!=="Tab")return;const items=focusable();if(!items.length)return;const first=items[0];const last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};root.addEventListener("keydown",keydown);return()=>{root.removeEventListener("keydown",keydown);previous?.focus()}},[]);
 return ref;
}
export function Dashboard({displayName,filterStorageId,initialWeek,previewData,defaultElement}:{displayName:string;filterStorageId:string;initialWeek?:string;previewData?:TimetablePayload;defaultElement?:TimetableElementSelection|null}) {
 const router=useRouter();
 const [week,setWeek]=useState(()=>initialWeek?mondayFor(new Date(`${initialWeek}T12:00:00`)):mondayFor());
 const [mode,setMode]=useState<TimetableViewMode>("week");
 const [day,setDay]=useState(Math.min(4,Math.max(0,(new Date().getDay()||1)-1)));
 const [data,setData]=useState<TimetablePayload|null>(previewData||null);
 const [timetableElements,setTimetableElements]=useState<TimetableElement[]>([]);
 const [selectedElement,setSelectedElement]=useState<TimetableElementSelection|null>(defaultElement||null);
 const [elementsBusy,setElementsBusy]=useState(!previewData);
 const [elementsError,setElementsError]=useState("");
 const [courseFilter,setCourseFilter]=useState<CourseFilter>({selectedCourseKeys:[],filterEnabled:false});
 const [selected,setSelected]=useState<Lesson|null>(null);
 const [filtersOpen,setFiltersOpen]=useState(false);
 const [courseSearch,setCourseSearch]=useState("");
 const [accountsOpen,setAccountsOpen]=useState(false);
 const [accounts,setAccounts]=useState<AccountSummary[]>([]);
 const [accountsBusy,setAccountsBusy]=useState(false);
 const [accountsError,setAccountsError]=useState("");
 const [switchingAccountId,setSwitchingAccountId]=useState("");
 const [logoutOpen,setLogoutOpen]=useState(false);
 const [logoutBusy,setLogoutBusy]=useState(false);
 const [logoutError,setLogoutError]=useState("");
 const [busy,setBusy]=useState(!previewData&&Boolean(defaultElement));
 const [error,setError]=useState("");
 const [offlineEnabled,setOfflineEnabled]=useState(false);
 const [isOnline,setIsOnline]=useState(true);
 const [isOfflineData,setIsOfflineData]=useState(false);
 const [lastUpdated,setLastUpdated]=useState<number|null>(null);
 const [clock,setClock]=useState(0);
 const [notificationsEnabled,setNotificationsEnabled]=useState(false);
 const [actionMessage,setActionMessage]=useState("");
 const filterStorageKey=useMemo(()=>courseFilterStorageKey(filterStorageId),[filterStorageId]);
 const selectionStorageKey=useMemo(()=>timetableSelectionStorageKey(filterStorageId),[filterStorageId]);
 const modeStorageKey=useMemo(()=>timetableViewModeStorageKey(filterStorageId),[filterStorageId]);
 const offlinePreferenceKey=useMemo(()=>offlineTimetablePreferenceKey(filterStorageId),[filterStorageId]);
 const notificationsPreferenceKey=useMemo(()=>notificationPreferenceKey(filterStorageId),[filterStorageId]);
 const load=useCallback(async(signal?:AbortSignal)=>{
  if(previewData){setData(previewData);setLastUpdated(Date.now());setBusy(false);return}
  if(!selectedElement){setBusy(false);return}
  setBusy(true);setError("");
  try {
   const response=await fetch(`/api/timetable?week=${isoDate(week)}&elementType=${selectedElement.type}&elementId=${selectedElement.id}`,{cache:"no-store",signal});
   const body=await response.json() as TimetablePayload&{error?:string};
   if(response.status===401){router.replace("/login");return}
   if(!response.ok)throw new Error(body.error);
   setData(body);setIsOfflineData(false);setLastUpdated(Date.now());
   if(offlineEnabled)await saveOfflineTimetable(filterStorageId,isoDate(week),selectedElement,body).catch(()=>{});
   if(notificationsEnabled&&typeof Notification!=="undefined")try{const snapshotKey=notificationSnapshotKey(filterStorageId,isoDate(week),selectedElement);const previousRaw=window.localStorage.getItem(snapshotKey);const previous=previousRaw?JSON.parse(previousRaw) as string[]:[];const fresh=newChanges(previous,body.lessons);window.localStorage.setItem(snapshotKey,JSON.stringify(changeSnapshot(body.lessons)));if(previousRaw&&fresh.length&&Notification.permission==="granted")new Notification(fresh.length===1?"Neue Stundenplanänderung":`${fresh.length} neue Stundenplanänderungen`,{body:fresh.slice(0,3).map(lesson=>`${names(lesson.su)}: ${lessonChangeSummary(lesson)}`).join("\n"),tag:`untiplan-${filterStorageId}`})}catch{}
  } catch(e) {
   if(signal?.aborted)return;
   const cached=offlineEnabled?await readOfflineTimetable(filterStorageId,isoDate(week),selectedElement).catch(()=>null):null;
   if(cached){setData(cached.data);setLastUpdated(cached.savedAt);setIsOfflineData(true);setError("")}else setError(e instanceof Error?e.message:"Stundenplan konnte nicht geladen werden.");
  } finally {if(!signal?.aborted)setBusy(false)}
 },[week,router,previewData,selectedElement,offlineEnabled,filterStorageId,notificationsEnabled]);
 useEffect(()=>{if(previewData)return;let ignore=false;(async()=>{setElementsBusy(true);setElementsError("");try{const response=await fetch(`/api/timetable/elements?date=${isoDate(week)}`,{cache:"no-store"});const body=await response.json();if(response.status===401){router.replace("/login");return}if(!response.ok)throw new Error(body.error);if(ignore)return;const discovered:TimetableElement[]=body.elements||[];const responseDefault:TimetableElementSelection|null=body.defaultElement||null;const complete=responseDefault&&!discovered.some(element=>element.id===responseDefault.id&&element.type===responseDefault.type)?[{...responseDefault,name:"Eigener Stundenplan"},...discovered]:discovered;const next=sortTimetableElements(complete);const stored=(()=>{try{return parseTimetableSelection(window.localStorage.getItem(selectionStorageKey))}catch{return null}})();const params=new URLSearchParams(window.location.search);const linked=parseTimetableSelection(JSON.stringify({type:Number(params.get("elementType")),id:Number(params.get("elementId"))}));setTimetableElements(next);setSelectedElement(current=>[linked,stored,current,responseDefault].find(candidate=>candidate&&next.some(element=>element.id===candidate.id&&element.type===candidate.type))||null)}catch(requestError){if(!ignore)setElementsError(requestError instanceof Error?requestError.message:"Verfügbare Stundenpläne konnten nicht geladen werden.")}finally{if(!ignore)setElementsBusy(false)}})();return()=>{ignore=true}},[previewData,router,selectionStorageKey,week]);
 // The effect synchronizes the selected week with the remote timetable API.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const controller=new AbortController();load(controller.signal);return()=>controller.abort()},[load]);
 useEffect(()=>{const update=()=>setIsOnline(navigator.onLine);update();window.addEventListener("online",update);window.addEventListener("offline",update);return()=>{window.removeEventListener("online",update);window.removeEventListener("offline",update)}},[]);
 useEffect(()=>{const update=()=>setClock(Date.now());const initial=window.setTimeout(update,0);const timer=window.setInterval(update,60000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[]);
 useEffect(()=>{if(previewData)return;const refresh=()=>{if(document.visibilityState==="visible"&&navigator.onLine)load()};const timer=window.setInterval(refresh,300000);document.addEventListener("visibilitychange",refresh);return()=>{window.clearInterval(timer);document.removeEventListener("visibilitychange",refresh)}},[load,previewData]);
 useEffect(()=>{const initial=window.setTimeout(()=>{try{setOfflineEnabled(window.localStorage.getItem(offlinePreferenceKey)==="true")}catch{}},0);return()=>window.clearTimeout(initial)},[offlinePreferenceKey]);
 useEffect(()=>{const initial=window.setTimeout(()=>{try{setNotificationsEnabled(window.localStorage.getItem(notificationsPreferenceKey)==="true"&&typeof Notification!=="undefined"&&Notification.permission==="granted")}catch{}},0);return()=>window.clearTimeout(initial)},[notificationsPreferenceKey]);
 useEffect(()=>{if(previewData)return;const initial=window.setTimeout(()=>{const linkedWeek=new URLSearchParams(window.location.search).get("week");if(linkedWeek&&/^\d{4}-\d{2}-\d{2}$/.test(linkedWeek))setWeek(mondayFor(new Date(`${linkedWeek}T12:00:00`)))},0);return()=>window.clearTimeout(initial)},[previewData]);
 useEffect(()=>{if(previewData||!selectedElement)return;const url=new URL(window.location.href);url.searchParams.set("week",isoDate(week));url.searchParams.set("elementType",String(selectedElement.type));url.searchParams.set("elementId",String(selectedElement.id));window.history.replaceState(null,"",url)},[previewData,selectedElement,week]);
 useEffect(()=>{if(previewData||!selectedElement)return;try{window.localStorage.setItem(selectionStorageKey,serializeTimetableSelection(selectedElement))}catch{}},[previewData,selectedElement,selectionStorageKey]);
 useEffect(()=>{try{
   // Each account keeps its preferred timetable view mode in this browser.
   // eslint-disable-next-line react-hooks/set-state-in-effect
   const stored=window.localStorage.getItem(modeStorageKey);setMode(stored?parseTimetableViewMode(stored):previewData?"week":"today");
  }catch{}},[modeStorageKey,previewData]);
 useEffect(()=>{try{window.localStorage.setItem(modeStorageKey,serializeTimetableViewMode(mode))}catch{}},[mode,modeStorageKey]);
 useEffect(()=>{try{
   // Each account owns a separate filter preference in this browser.
   // eslint-disable-next-line react-hooks/set-state-in-effect
   setCourseFilter(parseCourseFilter(window.localStorage.getItem(filterStorageKey)));
  }catch{}const sync=(event:StorageEvent)=>{if(event.key===filterStorageKey)setCourseFilter(parseCourseFilter(event.newValue))};window.addEventListener("storage",sync);return()=>window.removeEventListener("storage",sync)},[filterStorageKey]);
 const filteredLessons=useMemo(()=>applyCourseFilter(data?.lessons||[],courseFilter.selectedCourseKeys,courseFilter.filterEnabled),[data,courseFilter]);
 const lessonsByDay=useMemo(()=>weekDays.map((_,i)=>filteredLessons.filter(l=>l.date===dateNumber(addDays(week,i))).sort((a,b)=>a.startTime-b.startTime)),[filteredLessons,week]);
 const timelineBounds=useMemo(()=>timetableBounds(data?.timeGrid||[],filteredLessons),[data?.timeGrid,filteredLessons]);
 const importantChanges=useMemo(()=>changedLessons(filteredLessons),[filteredLessons]);
 const currentWeek=isoDate(week)===isoDate(mondayFor(new Date(clock)));
 const browserDay=new Date(clock).getDay();
 const todayIndex=Math.min(4,Math.max(0,browserDay-1));
 const todayLessons=previewData?lessonsByDay[day]:currentWeek&&browserDay>=1&&browserDay<=5?lessonsByDay[todayIndex]:[];
 const overviewDate=previewData?addDays(week,day):new Date(clock);
 const selectedElementType=selectedElement?.type||timetableElements[0]?.type||1;
 const elementsForSelectedType=timetableElements.filter(element=>element.type===selectedElementType);
 const courseOptions=useMemo(()=>{const availableCourses=data?.courses||[];const selectedKeys=new Set(courseFilter.selectedCourseKeys);const map=new Map<string,Course>(availableCourses.map(course=>[course.key,course]));for(const key of selectedKeys){if(!map.has(key)){map.set(key,{key,subjectId:0,teacherId:0,subject:`Ausgewählter Kurs (${key})`,teacher:"In dieser Woche nicht im Stundenplan"})}}return [...map.values()].sort((a,b)=>{const aSelected=selectedKeys.has(a.key)?0:1;const bSelected=selectedKeys.has(b.key)?0:1;return aSelected-bSelected||a.subject.localeCompare(b.subject,"de")||a.teacher.localeCompare(b.teacher,"de")})},[courseFilter.selectedCourseKeys,data?.courses]);
 const normalizedCourseSearch=courseSearch.trim().toLocaleLowerCase("de");
 const visibleCourseOptions=useMemo(()=>courseOptions.filter(course=>!normalizedCourseSearch||`${course.subject} ${course.teacher} ${course.key}`.toLocaleLowerCase("de").includes(normalizedCourseSearch)),[courseOptions,normalizedCourseSearch]);
 function saveFilters(keys:string[],enabled:boolean){const next=normalizeCourseFilter({selectedCourseKeys:keys,filterEnabled:enabled});setCourseFilter(next);try{window.localStorage.setItem(filterStorageKey,serializeCourseFilter(next))}catch{}}
 async function updateOffline(next:boolean){setOfflineEnabled(next);try{window.localStorage.setItem(offlinePreferenceKey,String(next));if(next&&data&&selectedElement)await saveOfflineTimetable(filterStorageId,isoDate(week),selectedElement,data);if(!next)clearOfflineTimetables(filterStorageId)}catch{setOfflineEnabled(false);setError("Der Offline-Speicher ist in diesem Browser nicht verfügbar.")}}
 async function updateNotifications(next:boolean){if(next&&(typeof Notification==="undefined"||await Notification.requestPermission()!=="granted")){setNotificationsEnabled(false);setError("Benachrichtigungen wurden in diesem Browser nicht freigegeben.");return}setNotificationsEnabled(next);try{window.localStorage.setItem(notificationsPreferenceKey,String(next));if(!next)for(let index=window.localStorage.length-1;index>=0;index-=1){const key=window.localStorage.key(index);if(key?.startsWith(`untiplan.change-snapshot.v1.${filterStorageId}.`))window.localStorage.removeItem(key)}}catch{}}
 function deleteCurrentAccountFilter(){setCourseFilter({selectedCourseKeys:[],filterEnabled:false});clearOfflineTimetables(filterStorageId);try{for(let index=window.localStorage.length-1;index>=0;index-=1){const key=window.localStorage.key(index);if(key?.startsWith(`untiplan.change-snapshot.v1.${filterStorageId}.`))window.localStorage.removeItem(key)}window.localStorage.removeItem(filterStorageKey);window.localStorage.removeItem(selectionStorageKey);window.localStorage.removeItem(modeStorageKey);window.localStorage.removeItem(offlinePreferenceKey);window.localStorage.removeItem(notificationsPreferenceKey);window.localStorage.removeItem(LEGACY_COURSE_FILTER_STORAGE_KEY)}catch{}}
 function showToday(){const now=previewData?new Date(Math.floor(previewData.range.startDate/10000),Math.floor(previewData.range.startDate%10000/100)-1,previewData.range.startDate%100):new Date();setWeek(mondayFor(now));setDay(Math.min(4,Math.max(0,(now.getDay()||1)-1)));setMode("today")}
 function exportCalendar(){downloadTextFile(`untiplan-${isoDate(week)}.ics`,lessonsToIcs(filteredLessons,`Untiplan · ${isoDate(week)}`),"text/calendar;charset=utf-8");setActionMessage("Kalenderdatei wurde erstellt.")}
 async function exportImage(){try{downloadBlob(`untiplan-${isoDate(week)}.png`,await timetablePng(filteredLessons,`Untiplan · ${week.toLocaleDateString("de-DE")}`));setActionMessage("Stundenplanbild wurde erstellt.")}catch(exportError){setError(exportError instanceof Error?exportError.message:"Bild konnte nicht erstellt werden.")}}
 async function sharePlan(){const text=timetableShareText(filteredLessons,"Mein Untiplan-Stundenplan");try{if(navigator.share)await navigator.share({title:"Untiplan",text,url:window.location.href});else{await navigator.clipboard.writeText(`${text}\n${window.location.href}`);setActionMessage("Plan und Link wurden kopiert.")}}catch(shareError){if(shareError instanceof DOMException&&shareError.name==="AbortError")return;setError("Der Stundenplan konnte nicht geteilt werden.")}}
 async function openAccounts(){setAccountsOpen(true);setAccountsBusy(true);setAccountsError("");try{const response=await fetch("/api/auth/accounts",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error);setAccounts(body.accounts||[])}catch(requestError){setAccountsError(requestError instanceof Error?requestError.message:"Konten konnten nicht geladen werden.")}finally{setAccountsBusy(false)}}
 async function switchToAccount(accountId:string){setSwitchingAccountId(accountId);setAccountsError("");try{const response=await fetch("/api/auth/switch",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accountId})});const body=await response.json();if(!response.ok)throw new Error(body.error);router.refresh()}catch(requestError){setAccountsError(requestError instanceof Error?requestError.message:"Konto konnte nicht gewechselt werden.");setSwitchingAccountId("")}}
 async function logout(){setLogoutBusy(true);setLogoutError("");try{const response=await fetch("/api/auth/logout",{method:"POST"});const body=await response.json();if(!response.ok)throw new Error();deleteCurrentAccountFilter();if(body.hasActiveAccount)router.refresh();else{router.replace("/login");router.refresh()}}catch{setLogoutError("Das Abmelden hat nicht geklappt. Bitte versuche es erneut.");setLogoutBusy(false)}}
 function openLogout(){setLogoutError("");setLogoutOpen(true)}
 function closeLogout(){if(!logoutBusy)setLogoutOpen(false)}
 return <div className="app-layout"><main className="app-shell">
  <header className="topbar"><a className="brand" href="/stundenplan"><Image className="brand-icon" src="/untiplan-logo.png" alt="" width={36} height={36} priority/><b>Untiplan</b></a><div className="user"><span>{displayName}</span><button className="ghost" onClick={openAccounts} aria-haspopup="dialog">Konten</button><button className="ghost" onClick={openLogout} aria-haspopup="dialog">Abmelden</button></div></header>
  <section className="toolbar"><div><p className="eyebrow">Stundenplan</p><h1>{week.toLocaleDateString("de-DE",{day:"2-digit",month:"long"})} – {addDays(week,4).toLocaleDateString("de-DE",{day:"2-digit",month:"long",year:"numeric"})}</h1>{data?.schoolYear&&<p className="muted">Schuljahr {data.schoolYear}{data.latestImportTime?` · WebUntis-Stand ${new Date(data.latestImportTime).toLocaleString("de-DE")}`:""}</p>}<p className="sync-status" role="status"><span className={isOnline?"online":"offline"}>{isOnline?"Online":"Offline"}</span>{lastUpdated?<span>Aktualisiert {relativeTime(lastUpdated,clock)}</span>:null}{isOfflineData?<b>Gespeicherter Stand</b>:null}</p></div><div className="toolbar-actions"><button className="ghost" onClick={()=>setWeek(addDays(week,-7))} aria-label="Vorherige Woche">←</button><button className="ghost" onClick={showToday}>Aktuelle Woche</button><button className="ghost" onClick={()=>setWeek(addDays(week,7))} aria-label="Nächste Woche">→</button><button className="ghost refresh-button" onClick={()=>load()} disabled={busy} aria-label="Stundenplan aktualisieren">{busy?"…":"↻"}</button><button className="filter-button" onClick={()=>setFiltersOpen(true)} aria-haspopup="dialog">Optionen{courseFilter.filterEnabled?` (${courseFilter.selectedCourseKeys.length})`:""} {courseFilter.filterEnabled?<span className="dot" aria-hidden="true"/>:null}</button></div></section>
  <nav className="view-tabs" role="tablist" aria-label="Stundenplanansicht"><button role="tab" aria-selected={mode==="today"} className={mode==="today"?"active":""} onClick={showToday}>Heute</button><button role="tab" aria-selected={mode==="week"} className={mode==="week"?"active":""} onClick={()=>setMode("week")}>Woche</button><button role="tab" aria-selected={mode==="day"} className={mode==="day"?"active":""} onClick={()=>setMode("day")}>Tag</button></nav>
  <div className="export-bar" aria-label="Stundenplan ausgeben"><button onClick={exportCalendar} disabled={!filteredLessons.length}>Kalender</button><button onClick={exportImage} disabled={!filteredLessons.length}>Bild</button><button onClick={()=>window.print()}>PDF/Drucken</button><button onClick={sharePlan} disabled={!filteredLessons.length}>Teilen</button></div>{actionMessage&&<p className="action-message" role="status">{actionMessage}</p>}
 {!previewData&&!elementsBusy&&timetableElements.length>0&&<div className="plan-picker" aria-label="Stundenplan auswählen"><label><span>Typ</span><select value={selectedElementType} onChange={event=>{const type=Number(event.target.value) as TimetableElementType;const first=timetableElements.find(element=>element.type===type);if(first){setSelectedElement({type:first.type,id:first.id});setSelected(null)}}}>{([1,2,3,4,5] as TimetableElementType[]).filter(type=>timetableElements.some(element=>element.type===type)).map(type=><option key={type} value={type}>{timetableElementLabels[type]}</option>)}</select></label><label className="plan-element-select"><span>Stundenplan</span><select value={selectedElement?.id||""} onChange={event=>{setSelectedElement({type:selectedElementType,id:Number(event.target.value)});setSelected(null)}}>{elementsForSelectedType.map(element=><option key={element.id} value={element.id}>{timetableElementLabel(element)}</option>)}</select></label></div>}
 {!previewData&&elementsError&&<p className="plan-picker-message error">{elementsError}</p>}
 {!previewData&&!elementsBusy&&!elementsError&&!timetableElements.length&&<p className="plan-picker-message muted">Für dieses Konto wurden keine auswählbaren Stundenpläne freigegeben.</p>}
 {previewData&&<div className="preview-notice"><b>Lokale Vorschau</b><span>Beispieldaten aus der gültigen WebUntis-Antwort · keine echte Abfrage</span></div>}
 {error&&<div className="notice error">{error}<button onClick={()=>load()}>Erneut versuchen</button></div>}{courseFilter.filterEnabled&&<div className={`filter-summary ${filteredLessons.length?"":"filter-empty"}`} role="status"><span>{filteredLessons.length?`${courseFilter.selectedCourseKeys.length} Kurse gefiltert · ${filteredLessons.length} Stunden sichtbar`:"Keine Stunden entsprechen deinem Kursfilter."}</span><button onClick={()=>saveFilters([],false)}>Filter zurücksetzen</button></div>}{mode!=="today"&&importantChanges.length>0&&<ChangesPanel lessons={importantChanges} onSelect={setSelected}/>} {busy||elementsBusy&&!data?<div className="loader">Stundenplan wird geladen …</div>:!previewData&&!selectedElement?<div className="empty">Kein Stundenplan ausgewählt.</div>:mode==="today"?<TodayOverview lessons={todayLessons} date={overviewDate} holidays={previewData||currentWeek?data?.holidays||[]:[]} bounds={timelineBounds} now={new Date(clock)} onSelect={setSelected}/>:mode==="week"?<div className="week-grid" aria-label="Wochenstundenplan">{weekDays.map((label,i)=><DayColumn key={label} label={label} date={addDays(week,i)} lessons={lessonsByDay[i]} holidays={data?.holidays||[]} bounds={timelineBounds} onSelect={setSelected}/>)}</div>:<><div className="day-tabs" role="tablist" aria-label="Wochentag auswählen">{weekDays.map((label,i)=><button key={label} role="tab" aria-selected={day===i} aria-label={label} className={day===i?"active":""} onClick={()=>setDay(i)}>{label.slice(0,2)}</button>)}</div><div className="day-view"><DayColumn label={weekDays[day]} date={addDays(week,day)} lessons={lessonsByDay[day]} holidays={data?.holidays||[]} bounds={timelineBounds} onSelect={setSelected}/></div></>}
 {filtersOpen&&data&&<FilterDialog courseFilter={courseFilter} courseOptions={courseOptions} visibleCourseOptions={visibleCourseOptions} courseSearch={courseSearch} setCourseSearch={setCourseSearch} saveFilters={saveFilters} offlineEnabled={offlineEnabled} updateOffline={updateOffline} notificationsEnabled={notificationsEnabled} updateNotifications={updateNotifications} close={()=>setFiltersOpen(false)}/>}
  {selected&&<LessonDialog lesson={selected} close={()=>setSelected(null)}/>} {accountsOpen&&<AccountDialog accounts={accounts} loading={accountsBusy} switchingAccountId={switchingAccountId} error={accountsError} close={()=>{if(!switchingAccountId)setAccountsOpen(false)}} switchAccount={switchToAccount}/>} {logoutOpen&&<LogoutDialog accountName={displayName} close={closeLogout} confirm={logout} busy={logoutBusy} error={logoutError}/>}</main><SiteFooter /></div> }
function TodayOverview({lessons,date,holidays,bounds,now,onSelect}:{lessons:Lesson[];date:Date;holidays:TimetablePayload["holidays"];bounds:TimelineBounds;now:Date;onSelect:(lesson:Lesson)=>void}) {
 const nowMinutes=now.getHours()*60+now.getMinutes();
 const active=lessons.find(lesson=>getLessonStatus(lesson)!=="cancelled"&&timeToMinutes(lesson.startTime)<=nowMinutes&&timeToMinutes(lesson.endTime)>nowMinutes);
 const next=lessons.find(lesson=>getLessonStatus(lesson)!=="cancelled"&&timeToMinutes(lesson.startTime)>nowMinutes);
 const last=[...lessons].filter(lesson=>getLessonStatus(lesson)!=="cancelled").sort((a,b)=>b.endTime-a.endTime)[0];
 const changes=changedLessons(lessons);
 const focus=active||next;
 const weekend=date.getDay()===0||date.getDay()===6;
 return <section className="today-overview" aria-labelledby="today-title"><div className="today-heading"><div><p className="eyebrow">Dein Tag</p><h2 id="today-title">{date.toLocaleDateString("de-DE",{weekday:"long",day:"2-digit",month:"long"})}</h2></div><span>{date.toLocaleDateString("de-DE",{day:"2-digit"})}</span></div><div className="today-cards"><article><small>{active?"Gerade":"Als Nächstes"}</small><b>{focus?names(focus.su):weekend?"Wochenende":"Kein Unterricht mehr"}</b><span>{focus?`${formatTime(focus.startTime)}–${formatTime(focus.endTime)}`:"Freier Nachmittag"}</span></article><article><small>Unterrichtsende</small><b>{last?`${formatTime(last.endTime)} Uhr`:"–"}</b><span>{lessons.length?`${lessons.length} Termine heute`:"Keine Termine"}</span></article><article className={changes.length?"has-changes":""}><small>Änderungen</small><b>{changes.length}</b><span>{changes.length?"Details im Tagesplan":"Alles nach Plan"}</span></article></div>{weekend?<div className="empty today-empty">Heute ist kein regulärer Unterrichtstag.</div>:<div className="day-view"><DayColumn label="Heute" date={date} lessons={lessons} holidays={holidays} bounds={bounds} onSelect={onSelect}/></div>}</section>
}
function ChangesPanel({lessons,onSelect}:{lessons:Lesson[];onSelect:(lesson:Lesson)=>void}){return <section className="changes-panel" aria-labelledby="changes-title"><div className="changes-head"><div><p className="eyebrow">Wichtige Änderungen</p><h2 id="changes-title">{lessons.length} {lessons.length===1?"Änderung":"Änderungen"} in dieser Woche</h2></div><span aria-hidden="true">!</span></div><div className="change-list">{lessons.map(lesson=><button key={`${lesson.id}-${lesson.date}-${lesson.startTime}`} onClick={()=>onSelect(lesson)}><b>{names(lesson.su)}</b><span>{new Date(Math.floor(lesson.date/10000),Math.floor(lesson.date%10000/100)-1,lesson.date%100).toLocaleDateString("de-DE",{weekday:"short"})} · {formatTime(lesson.startTime)}</span><small>{lessonChangeSummary(lesson)}</small></button>)}</div></section>}
function DayColumn({label,date,lessons,holidays,bounds,onSelect}:{label:string;date:Date;lessons:Lesson[];holidays:TimetablePayload["holidays"];bounds:TimelineBounds;onSelect:(l:Lesson)=>void}){const dayHolidays=holidaysForDate(holidays,dateNumber(date));const positioned=positionLessons(lessons);const scale=1.15;const timelineHeight=Math.max(120,(bounds.end-bounds.start)*scale);const hourMarks:Array<{minute:number;label:string}>=[];for(let minute=Math.ceil(bounds.start/60)*60;minute<bounds.end;minute+=60)hourMarks.push({minute,label:`${String(Math.floor(minute/60)).padStart(2,"0")}:00`});return <section className="day-column"><header><b>{label}</b><span>{date.toLocaleDateString("de-DE",{day:"2-digit",month:"2-digit"})}</span></header>{dayHolidays.map(holiday=><div className="holiday-banner" key={holiday.id}><b>{holiday.name}</b>{holiday.longName&&holiday.longName!==holiday.name?<span>{holiday.longName}</span>:null}</div>)}<div className="lesson-timeline" style={{height:timelineHeight}}>{hourMarks.map(mark=><div className="hour-line" key={mark.minute} style={{top:(mark.minute-bounds.start)*scale}}><span>{mark.label}</span></div>)}{positioned.map(({lesson,column,columnCount,start,end})=><button key={`${lesson.id}-${lesson.startTime}`} className={`lesson timeline-lesson ${getLessonStatus(lesson)}`} style={{top:(start-bounds.start)*scale,height:Math.max(48,(end-start)*scale),left:`calc(${column/columnCount*100}% + 3px)`,width:`calc(${100/columnCount}% - 6px)`}} onClick={()=>onSelect(lesson)}><span className="time">{formatTime(lesson.startTime)}–{formatTime(lesson.endTime)}</span><strong>{names(lesson.su)}</strong><span>{names(lesson.te)}</span><span className="room">{names(lesson.ro)}</span>{getLessonStatus(lesson)!=="normal"&&<em>{getLessonStatus(lesson)==="cancelled"?"Entfällt":getLessonStatus(lesson)==="substitution"?"Vertretung":"Änderung"}</em>}</button>)}{!lessons.length&&!dayHolidays.length?<div className="timeline-empty empty">Keine Stunden</div>:null}</div></section>}
function FilterDialog({courseFilter,courseOptions,visibleCourseOptions,courseSearch,setCourseSearch,saveFilters,offlineEnabled,updateOffline,notificationsEnabled,updateNotifications,close}:{courseFilter:CourseFilter;courseOptions:Course[];visibleCourseOptions:Course[];courseSearch:string;setCourseSearch:(value:string)=>void;saveFilters:(keys:string[],enabled:boolean)=>void;offlineEnabled:boolean;updateOffline:(enabled:boolean)=>void;notificationsEnabled:boolean;updateNotifications:(enabled:boolean)=>void;close:()=>void}) {
 const ref=useModalFocus(close);
 return <div className="overlay" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><aside ref={ref} className="drawer" role="dialog" aria-modal="true" aria-labelledby="filter-title"><div className="drawer-head"><div><p className="eyebrow">Ansicht anpassen</p><h2 id="filter-title">Optionen</h2></div><button className="icon-button" onClick={close} aria-label="Optionen schließen">×</button></div><section className="option-section"><h3>Offline & Änderungen</h3><label className="switch-row"><span><b>Stundenpläne speichern</b><small>Geladene Wochen verschlüsselt auf diesem Gerät verfügbar machen</small></span><input type="checkbox" checked={offlineEnabled} onChange={event=>updateOffline(event.target.checked)}/></label><label className="switch-row"><span><b>Änderungen melden</b><small>Bei Aktualisierungen über neu erkannte Änderungen informieren</small></span><input type="checkbox" checked={notificationsEnabled} onChange={event=>updateNotifications(event.target.checked)}/></label></section><section className="option-section"><h3>Kursfilter</h3><label className="switch-row"><span><b>Filter aktivieren</b><small>Nur ausgewählte Kurse auf diesem Gerät anzeigen</small></span><input type="checkbox" checked={courseFilter.filterEnabled} disabled={!courseFilter.selectedCourseKeys.length} onChange={event=>saveFilters(courseFilter.selectedCourseKeys,event.target.checked)}/></label><label className="course-search"><span>Kurse suchen</span><input type="search" value={courseSearch} onChange={event=>setCourseSearch(event.target.value)} placeholder="Fach, Lehrkraft oder Schlüssel" /></label><div className="course-list">{courseOptions.length?visibleCourseOptions.length?visibleCourseOptions.map(course=><label key={course.key} className="course-option"><input type="checkbox" checked={courseFilter.selectedCourseKeys.includes(course.key)} onChange={event=>saveFilters(event.target.checked?[...courseFilter.selectedCourseKeys,course.key]:courseFilter.selectedCourseKeys.filter(key=>key!==course.key),event.target.checked||courseFilter.selectedCourseKeys.length>1?courseFilter.filterEnabled:false)}/><span><b>{course.subject}</b><small>{course.teacher}</small></span></label>):<p className="muted">Keine Kurse für die Suche gefunden.</p>:<p className="muted">In diesem Zeitraum wurden keine Kurse gefunden.</p>}</div><button className="ghost full" onClick={()=>saveFilters([],false)}>Filter zurücksetzen</button></section></aside></div>
}
function LessonDialog({lesson,close}:{lesson:Lesson;close:()=>void}) {
 const status=getLessonStatus(lesson);const ref=useModalFocus(close);
 return <div className="overlay dialog-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><article ref={ref} className="dialog" role="dialog" aria-modal="true" aria-labelledby="lesson-title"><div className="drawer-head"><div><p className="eyebrow">Unterrichtsdetails</p><h2 id="lesson-title">{names(lesson.su)}</h2></div><button className="icon-button" onClick={close} aria-label="Unterrichtsdetails schließen">×</button></div><span className={`status ${status}`}>{status==="cancelled"?"Ausfall":status==="substitution"?"Vertretung":status==="normal"?"Planmäßig":"Geändert"}</span>{status!=="normal"&&<p className="change-detail">{lessonChangeSummary(lesson)}</p>}<dl><div><dt>Zeit</dt><dd>{formatTime(lesson.startTime)}–{formatTime(lesson.endTime)} Uhr</dd></div><div><dt>Lehrkraft</dt><dd>{names(lesson.te)}</dd></div><div><dt>Raum</dt><dd>{names(lesson.ro)}</dd></div><div><dt>Klasse</dt><dd>{names(lesson.kl)}</dd></div><div><dt>Gruppe</dt><dd>{lesson.sg||"–"}</dd></div><div><dt>Hinweis</dt><dd>{lesson.substText||lesson.info||lesson.lstext||"–"}</dd></div></dl><div className="dialog-actions"><button className="primary" onClick={()=>downloadTextFile(`untiplan-${lesson.date}-${lesson.startTime}.ics`,lessonsToIcs([lesson],names(lesson.su)),"text/calendar;charset=utf-8")}>Zum Kalender hinzufügen</button></div></article></div>
}
function AccountDialog({accounts,loading,switchingAccountId,error,close,switchAccount}:{accounts:AccountSummary[];loading:boolean;switchingAccountId:string;error:string;close:()=>void;switchAccount:(accountId:string)=>void}){const ref=useModalFocus(close);return <div className="overlay dialog-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><article ref={ref} className="account-dialog" role="dialog" aria-modal="true" aria-labelledby="accounts-title"><div className="drawer-head"><div><p className="eyebrow">Angemeldete Konten</p><h2 id="accounts-title">Konto wechseln</h2></div><button className="icon-button" onClick={close} disabled={Boolean(switchingAccountId)} aria-label="Konten schließen">×</button></div><p className="muted account-hint">Jedes Konto behält seinen eigenen Kursfilter.</p>{loading?<div className="account-loading">Konten werden geladen …</div>:<div className="account-list">{accounts.map(account=><button key={account.id} className={`account-option ${account.active?"active":""}`} onClick={()=>switchAccount(account.id)} disabled={account.active||Boolean(switchingAccountId)}><span className="account-avatar" aria-hidden="true">{account.displayName.trim().charAt(0).toLocaleUpperCase("de")||"?"}</span><span className="account-copy"><b>{account.displayName}</b><small>{account.username} · {account.school}</small></span><span className="account-state">{account.active?"Aktiv":switchingAccountId===account.id?"Wechsel …":"Wechseln"}</span></button>)}</div>}{error&&<p className="logout-error" role="alert">{error}</p>}<a className="primary account-add" href="/login?add=1">+ Weiteres Konto hinzufügen</a></article></div>}
function LogoutDialog({accountName,close,confirm,busy,error}:{accountName:string;close:()=>void;confirm:()=>void;busy:boolean;error:string}){const ref=useModalFocus(close);return <div className="overlay dialog-overlay logout-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><article ref={ref} className="logout-dialog" role="alertdialog" aria-modal="true" aria-labelledby="logout-title" aria-describedby="logout-description"><div className="logout-icon" aria-hidden="true">!</div><div className="logout-copy"><p className="eyebrow">Konto abmelden</p><h2 id="logout-title">Wirklich abmelden?</h2><p id="logout-description" className="muted">Du meldest das Konto <strong>„{accountName}“</strong> ab. Der zugehörige Kursfilter wird auf diesem Gerät gelöscht. Deine anderen Konten und Filter bleiben unverändert.</p>{error&&<p className="logout-error" role="alert">{error}</p>}</div><div className="logout-actions"><button className="ghost" onClick={close} disabled={busy}>Abbrechen</button><button className="danger-button" onClick={confirm} disabled={busy}>{busy?"Wird abgemeldet …":"Konto abmelden"}</button></div></article></div>}
